### PR TITLE
Create Microsoft Azure strategy

### PR DESCRIPTION
**Pull request by juhanakristian**
Adds Microsoft Azure login strategy. Pretty much the same as GoogleStrategy but with the possibility to define a tenant if needed.

### CODE REVIEW

**Comment by sergiodxa** [comment]
Thanks for the PR @juhanakristian!

I have a few questions since I don't know anything about Azure or MS.

1. Is this to login with your Azure account? So the account you use to access the Azure panel? Or with a Microsoft account you could use with other MS services (like a `@hotmail.com` account but modern)
2. Could you write some basic docs? I think you can copy GoogleStrategy and just mention Azure and put a link to where you could get the client ID and secret, and maybe document the tenant part.
3. Could you give me a link to the OAuth2 docs of Azure? I want to use it to review the strategy, so far the code looks great :+1:

**Comment by juhanakristian** [comment]
Hi @sergiodxa I'll try to answer as best as I can

1. This is for logging with [Microsoft Identity](https://docs.microsoft.com/en-us/azure/active-directory/develop/), so either work/school account tied to Azure Active Directory or personal Microsoft account (XBox, Skype, outlook.com)
2. Sure, I can write some docs. At least the `tenant` value might need some clarification (it's basically a way to enable the login to members of a single organization)
3. [Here's](https://docs.microsoft.com/fi-fi/azure/active-directory/develop/active-directory-v2-protocols) the docs for OAuth2 and [here](https://docs.microsoft.com/fi-fi/azure/active-directory/develop/v2-oauth2-auth-code-flow) is the docs for the OAuth2 authorization code flow

TBH I'm not sure if _AzureStrategy_ is the best name for this. Azure might be familiar to people developing enterprise apps so changing the name to _MicrosoftStrategy_ might be worth considering.

**Comment by afoures** [comment]
@juhanakristian does this works with on-premises Active Directory ?

**Comment by juhanakristian** [comment]
@afoures Unfortunately it doesn't. I'm not too familiar with on-premises Active Directory so I'm not sure what differences there are.

**Comment by sergiodxa** [comment]
@juhanakristian hey! thanks for taking the time to work on this strategy.

Since v3 strategies are not going to live inside this packages anymore (old strategies are still in the repo so people can copy them) and instead they will be published in independent packages like remix-auth-oauth2 or remix-auth-github.

I suggest you to use the template repository http://github.com/sergiodxa/remix-auth-strategy-template to create a `remix-auth-azure` repo, copy your code there (install `remix-auth-oauth2`) and publish it to npm by yourself.

Again, thanks for the work here and I hope to see a new remix-auth-azure package soon!

**Pull request closed without merging**
